name: CI
on:
  push:
    branches:
      - master
      - test-nimble
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nimble-version: 08be587ad79f1692d5adcb03ce0a13dfda5d8818
      test-command: |
        nimble --useSystemNim install -y --depsOnly toml_serialization json_serialization unittest2
        nimble list --installed --version
        rm -f nimble.lock
        nimble test
