name: CI
on:
  push:
    branches:
      - master
      - nimble_test
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nimble-version: #02baf22243761272116d4393a80f693a439163f2
      test-command: |
        nimble --useSystemNim install -y --depsOnly toml_serialization json_serialization unittest2
        nimble list --installed --version
        rm -f nimble.lock
        nimble test
